# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#         with:
#           install: true
#           driver: docker-container
#           use: true

#       - name: Create and bootstrap the builder
#         run: |
#           docker buildx create --name mybuilder --use
#           docker buildx inspect --bootstrap

#       - name: List Docker Builders
#         run: |
#           docker buildx ls

#       - name: Inspect Builder
#         run: |
#           docker buildx inspect mybuilder

#       - name: Log in to Azure
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Log in to Azure Container Registry
#         run: |
#           az acr login --name ${{ secrets.AZURE_ACR_LOGIN_SERVER }}

#       - name: Build and push Docker image
#         run: |
#           docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/myfastapiapp:latest --push .

#   deploy:
#     name: Continuous Deployment
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Set up Kubernetes
#         uses: azure/aks-set-context@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#           cluster-name: CusSeg
#           resource-group: Customer_Seg_Deployment

#       - name: Deploy to AKS
#         run: |
#           kubectl set image deployment/fastapi-app fastapi-container=${{ secrets.AZURE_ACR_LOGIN_SERVER }}/myfastapiapp:latest
#           kubectl rollout status deployment/fastapi-app
