name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver: docker-container
          use: true

      - name: Create and bootstrap the builder
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.AZURE_CR_PASSWORD }} | docker login ${{ secrets.AZURE_CR_LOGIN_SERVER }} -u ${{ secrets.AZURE_CR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 -t ${{ secrets.AZURE_CR_LOGIN_SERVER }}/myfastapiapp:latest --push .
